# adapted from:
#  https://til.simonwillison.net/pypi/pypi-releases-from-github
#  https://github.com/snok/install-poetry
#  https://jacobian.org/til/github-actions-poetry/

name: Release Version

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: package
    concurrency: release

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_VERSION_BUMP_APP_ID }}
          private-key: ${{ secrets.RELEASE_VERSION_BUMP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ steps.app-token.outputs.token }}

      - name: TypeScript Semantic Release
        if: github.ref == 'refs/heads/main'
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
