# adapted from:
#  https://til.simonwillison.net/pypi/pypi-releases-from-github
#  https://github.com/snok/install-poetry
#  https://jacobian.org/til/github-actions-poetry/

name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          uv sync --group dev

      - name: Test with python ${{ matrix.python-version }}
        run: uv run --frozen pytest

  buntest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install test dependencies
        run: bun install

      - name: Test with bun
        run: bun test
